blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Serpensin/HypeRate-Python/blob/master/README.md
    about: Check the documentation for usage examples and API reference